// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WebteeClient is the client API for Webtee service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebteeClient interface {
	SendLog(ctx context.Context, opts ...grpc.CallOption) (Webtee_SendLogClient, error)
}

type webteeClient struct {
	cc grpc.ClientConnInterface
}

func NewWebteeClient(cc grpc.ClientConnInterface) WebteeClient {
	return &webteeClient{cc}
}

func (c *webteeClient) SendLog(ctx context.Context, opts ...grpc.CallOption) (Webtee_SendLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &Webtee_ServiceDesc.Streams[0], "/Webtee/SendLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &webteeSendLogClient{stream}
	return x, nil
}

type Webtee_SendLogClient interface {
	Send(*LogLine) error
	CloseAndRecv() (*ReceiveResponse, error)
	grpc.ClientStream
}

type webteeSendLogClient struct {
	grpc.ClientStream
}

func (x *webteeSendLogClient) Send(m *LogLine) error {
	return x.ClientStream.SendMsg(m)
}

func (x *webteeSendLogClient) CloseAndRecv() (*ReceiveResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReceiveResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WebteeServer is the server API for Webtee service.
// All implementations must embed UnimplementedWebteeServer
// for forward compatibility
type WebteeServer interface {
	SendLog(Webtee_SendLogServer) error
	mustEmbedUnimplementedWebteeServer()
}

// UnimplementedWebteeServer must be embedded to have forward compatible implementations.
type UnimplementedWebteeServer struct {
}

func (UnimplementedWebteeServer) SendLog(Webtee_SendLogServer) error {
	return status.Errorf(codes.Unimplemented, "method SendLog not implemented")
}
func (UnimplementedWebteeServer) mustEmbedUnimplementedWebteeServer() {}

// UnsafeWebteeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebteeServer will
// result in compilation errors.
type UnsafeWebteeServer interface {
	mustEmbedUnimplementedWebteeServer()
}

func RegisterWebteeServer(s grpc.ServiceRegistrar, srv WebteeServer) {
	s.RegisterService(&Webtee_ServiceDesc, srv)
}

func _Webtee_SendLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WebteeServer).SendLog(&webteeSendLogServer{stream})
}

type Webtee_SendLogServer interface {
	SendAndClose(*ReceiveResponse) error
	Recv() (*LogLine, error)
	grpc.ServerStream
}

type webteeSendLogServer struct {
	grpc.ServerStream
}

func (x *webteeSendLogServer) SendAndClose(m *ReceiveResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *webteeSendLogServer) Recv() (*LogLine, error) {
	m := new(LogLine)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Webtee_ServiceDesc is the grpc.ServiceDesc for Webtee service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Webtee_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Webtee",
	HandlerType: (*WebteeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendLog",
			Handler:       _Webtee_SendLog_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "logs.proto",
}
