name: 'go-scripts'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      
      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v3
        with: 
          version: v1.54
          args: --issues-exit-code=1 

      - name: Run format and vet
        run: |
          make format
          make vet
      
      - name: Run Tests
        run:
          make test
