name: "Golang Lint"

on:
  pull_request:
    branches:
      - main

jobs:
  golangci-lint:
    runs-on: ubuntu-22.04-htzhel1-ax42-a
    steps:
      - name: Checkout code
        uses: https://gitea.obmondo.com/Obmondo/checkout@v4.3.0

      - name: Setup Go
        uses: https://gitea.obmondo.com/Obmondo/setup-go@v6.0.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Golang CI lint
        uses: https://gitea.obmondo.com/Obmondo/golangci-lint-action@v8.0.0
        with:
          version: v2.5.0
          args: --timeout=5m --config=.golangci.yml
